In [ ]:
import pandas as pd

# Read the two CSV files
df1 = pd.read_csv('/content/gymnastics1.csv')
df2 = pd.read_csv('/content/gymnastics2.csv')

# Concatenate the two dataframes
df = pd.concat([df1, df2], ignore_index=True)

print("Dữ liệu sau khi nối:")
display(df.head())
print(f"Kích thước dữ liệu ban đầu: {df.shape}")

Dữ liệu sau khi nối:

   Duration          Date  Pulse  Maxpulse  Calories
0       NaN  '2020/11/12'    NaN       NaN       NaN
1       NaN  '2020/11/13'    NaN       NaN     269.0
2      60.0  '2020/11/14'    NaN       NaN       NaN
3      60.0           NaN  100.0       NaN       NaN
4      60.0  '2020/11/16'  100.0     120.0     255.7

Kích thước dữ liệu ban đầu: (54, 5)

### Xóa các dòng dữ liệu trùng lặp

In [ ]:
initial_rows = df.shape[0]
duplicates_count = df.duplicated().sum()
df.drop_duplicates(inplace=True)
removed_duplicates = initial_rows - df.shape[0]

print(f"Số lượng dòng trùng lặp đã bị xóa: {removed_duplicates}")
print(f"Kích thước dữ liệu sau khi xóa trùng lặp: {df.shape}")

Số lượng dòng trùng lặp đã bị xóa: 3
Kích thước dữ liệu sau khi xóa trùng lặp: (51, 5)

### Lấy ra tất cả các dòng có ít nhất 1 ô dữ liệu trống

In [ ]:
rows_with_any_null = df[df.isnull().any(axis=1)]

print(f"Số lượng dòng có ít nhất 1 ô dữ liệu trống: {rows_with_any_null.shape[0]}")
display(rows_with_any_null.head())

Số lượng dòng có ít nhất 1 ô dữ liệu trống: 15

   Duration          Date  Pulse  Maxpulse  Calories
0       NaN  '2020/11/12'    NaN       NaN       NaN
1       NaN  '2020/11/13'    NaN       NaN     269.0
2      60.0  '2020/11/14'    NaN       NaN       NaN
3      60.0           NaN  100.0       NaN       NaN
8      60.0           NaN  100.0     120.0     300.0

### Xóa các dòng có ít nhất 3 ô dữ liệu trống

In [ ]:
initial_rows_before_drop = df.shape[0]
df.dropna(thresh=df.shape[1] - 2, inplace=True) # Keep rows with at least df.shape[1] - 2 non-NaN values
removed_rows_with_3_or_more_nulls = initial_rows_before_drop - df.shape[0]

# Reset index to ensure contiguous integer indexing for subsequent operations
df.reset_index(drop=True, inplace=True)

print(f"Số lượng dòng có ít nhất 3 ô dữ liệu trống đã bị xóa: {removed_rows_with_3_or_more_nulls}")
print(f"Kích thước dữ liệu sau khi xóa các dòng có nhiều ô trống: {df.shape}")

Số lượng dòng có ít nhất 3 ô dữ liệu trống đã bị xóa: 0
Kích thước dữ liệu sau khi xóa các dòng có nhiều ô trống: (47, 6)

### Chuẩn hóa cột thời gian tập (Duration) thành số nguyên

In [ ]:
df['Duration'] = pd.to_numeric(df['Duration'], errors='coerce')
df['Duration'] = df['Duration'].astype('Int64') # Use Int64 to handle potential NaN values after conversion

print("Kiểu dữ liệu của cột 'Duration' sau khi chuẩn hóa:")
display(df['Duration'].dtype)
display(df.head())

Kiểu dữ liệu của cột 'Duration' sau khi chuẩn hóa:

Int64Dtype()

    Duration          Date  Pulse  Maxpulse  Calories
4         60  '2020/11/16'  100.0     120.0     255.7
5         60  '2020/11/17'  107.0     129.0     347.3
8         60           NaN  100.0     120.0     300.0
9         45  '2020/11/18'   88.0     110.0       NaN
10        45  '2020/11/19'   99.0     119.0     283.0

### Điền giá trị trống trong cột 'Calories' bằng trung bình cộng

In [ ]:
mean_calories = df['Calories'].mean()
df['Calories'].fillna(mean_calories, inplace=True)

print(f"Giá trị trung bình của 'Calories' được sử dụng để điền: {mean_calories:.2f}")
print("Số lượng ô trống trong cột 'Calories' sau khi điền:", df['Calories'].isnull().sum())
display(df.head())

Giá trị trung bình của 'Calories' được sử dụng để điền: 300.05
Số lượng ô trống trong cột 'Calories' sau khi điền: 0

/tmp/ipykernel_2989/646740067.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Calories'].fillna(mean_calories, inplace=True)

    Duration          Date  Pulse  Maxpulse    Calories
4         60  '2020/11/16'  100.0     120.0  255.700000
5         60  '2020/11/17'  107.0     129.0  347.300000
8         60           NaN  100.0     120.0  300.000000
9         45  '2020/11/18'   88.0     110.0  300.046512
10        45  '2020/11/19'   99.0     119.0  283.000000

### Điền giá trị trống trong cột 'Pulse' theo phương thức ffill

In [ ]:
df['Pulse'].fillna(method='ffill', inplace=True)

print("Số lượng ô trống trong cột 'Pulse' sau khi điền:", df['Pulse'].isnull().sum())
display(df.head())

Số lượng ô trống trong cột 'Pulse' sau khi điền: 0

/tmp/ipykernel_2989/1928296405.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Pulse'].fillna(method='ffill', inplace=True)
/tmp/ipykernel_2989/1928296405.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Pulse'].fillna(method='ffill', inplace=True)

    Duration          Date  Pulse  Maxpulse    Calories
4         60  '2020/11/16'  100.0     120.0  255.700000
5         60  '2020/11/17'  107.0     129.0  347.300000
8         60           NaN  100.0     120.0  300.000000
9         45  '2020/11/18'   88.0     110.0  300.046512
10        45  '2020/11/19'   99.0     119.0  283.000000

### Chuẩn hóa cột 'Date' và xử lý các ô trống

In [ ]:
# Convert 'Date' to datetime, coercing errors to NaT
df['Date_dt'] = pd.to_datetime(df['Date'], errors='coerce')

rows_to_drop = []
filled_count = 0

# Iterate over the DataFrame's index directly to find NaT values
for current_idx in df[df['Date_dt'].isnull()].index:
    prev_date = None
    next_date = None

    # Try to get the previous valid date using positional indexing
    if current_idx > 0:
        for i in range(1, current_idx + 1):
            if pd.notna(df.loc[current_idx - i, 'Date_dt']):
                prev_date = df.loc[current_idx - i, 'Date_dt']
                break

    # Try to get the next valid date using positional indexing
    if current_idx < len(df) - 1:
        for i in range(1, len(df) - current_idx):
            if pd.notna(df.loc[current_idx + i, 'Date_dt']):
                next_date = df.loc[current_idx + i, 'Date_dt']
                break

    if prev_date is not None and next_date is not None:
        # Check if the dates are a-1 and a+1
        if prev_date + pd.Timedelta(days=2) == next_date:
            df.loc[current_idx, 'Date_dt'] = prev_date + pd.Timedelta(days=1)
            filled_count += 1
        else:
            rows_to_drop.append(current_idx)
    else:
        rows_to_drop.append(current_idx)

# Drop rows that could not be filled
df.drop(rows_to_drop, inplace=True)
print(f"Số lượng hàng bị xóa vì không thể điền ngày: {len(rows_to_drop)}")
print(f"Số lượng ngày được điền dựa trên ngày trước và sau: {filled_count}")

# Convert the cleaned datetime objects back to YYYY/MM/DD string format
df['Date'] = df['Date_dt'].dt.strftime('%Y/%m/%d')

# Drop the temporary datetime column
df.drop(columns=['Date_dt'], inplace=True)

print("Số lượng ô trống trong cột 'Date' sau khi xử lý:", df['Date'].isnull().sum())
display(df.head())

Số lượng hàng bị xóa vì không thể điền ngày: 1
Số lượng ngày được điền dựa trên ngày trước và sau: 2
Số lượng ô trống trong cột 'Date' sau khi xử lý: 0

   Duration        Date  Pulse  Maxpulse    Calories
0        60  2020/11/16  100.0     120.0  255.700000
1        60  2020/11/17  107.0     129.0  347.300000
3        45  2020/11/18   88.0     110.0  300.046512
4        45  2020/11/19   99.0     119.0  283.000000
5        45  2020/11/20   95.0     120.0  233.700000

### Cắt giá trị của cột 'Duration' nếu lớn hơn 120

In [ ]:
df['Duration'] = df['Duration'].apply(lambda x: 120 if x > 120 else x)

print("Các giá trị 'Duration' lớn hơn 120 đã được thay thế bằng 120.")
display(df.head())
print(f"Kích thước dữ liệu cuối cùng: {df.shape}")

Các giá trị 'Duration' lớn hơn 120 đã được thay thế bằng 120.

    Duration          Date  Pulse  Maxpulse    Calories    Date_dt
4         60  '2020/11/16'  100.0     120.0  255.700000 2020-11-16
5         60  '2020/11/17'  107.0     129.0  347.300000 2020-11-17
8         60           NaN  100.0     120.0  300.000000        NaT
9         45  '2020/11/18'   88.0     110.0  300.046512 2020-11-18
10        45  '2020/11/19'   99.0     119.0  283.000000 2020-11-19

Kích thước dữ liệu cuối cùng: (47, 6)

### Tổng số buổi luyện tập, tổng thời gian luyện tập, và tổng lượng calories tiêu thụ

In [ ]:
total_sessions = df.shape[0]
total_duration = df['Duration'].sum()
total_calories = df['Calories'].sum()

print(f"Tổng số buổi luyện tập: {total_sessions}")
print(f"Tổng số thời gian luyện tập (phút): {total_duration}")
print(f"Tổng lượng calories tiêu thụ: {total_calories:.2f}")

Tổng số buổi luyện tập: 54
Tổng số thời gian luyện tập (phút): 3315.0
Tổng lượng calories tiêu thụ: 14147.60

### Tính % số buổi có nhịp tim cực đại (Maxpulse) trên 130

In [ ]:
sessions_high_maxpulse = df[df['Maxpulse'] > 130].shape[0]
percentage_high_maxpulse = (sessions_high_maxpulse / total_sessions) * 100

print(f"Số buổi có nhịp tim cực đại (Maxpulse) trên 130: {sessions_high_maxpulse}")
print(f"Phần trăm số buổi có nhịp tim cực đại trên 130: {percentage_high_maxpulse:.2f}%")

Số buổi có nhịp tim cực đại (Maxpulse) trên 130: 16
Phần trăm số buổi có nhịp tim cực đại trên 130: 29.63%

### Thêm cột 'Calories per minute'

In [ ]:
# Handle potential division by zero for 'Duration'
df['Calories per minute'] = df.apply(lambda row: row['Calories'] / row['Duration'] if row['Duration'] != 0 else 0, axis=1)

print("Đã thêm cột 'Calories per minute'.")
display(df.head())

Đã thêm cột 'Calories per minute'.

   Duration          Date  Pulse  Maxpulse  Calories  Calories per minute
0       NaN  '2020/11/12'    NaN       NaN       NaN                  NaN
1       NaN  '2020/11/13'    NaN       NaN     269.0                  NaN
2      60.0  '2020/11/14'    NaN       NaN       NaN                  NaN
3      60.0           NaN  100.0       NaN       NaN                  NaN
4      60.0  '2020/11/16'  100.0     120.0     255.7             4.261667

### Nhóm những ngày tập 60 phút và 45 phút. Tính giá trị min, max và giá trị trung bình Calories per minute trong mỗi nhóm.

In [ ]:
duration_groups = df[df['Duration'].isin([45, 60])]

calories_per_minute_summary = duration_groups.groupby('Duration')['Calories per minute'].agg(['min', 'max', 'mean']).reset_index()

print("Giá trị min, max và trung bình 'Calories per minute' cho các buổi tập 45 và 60 phút:")
display(calories_per_minute_summary)

Giá trị min, max và trung bình 'Calories per minute' cho các buổi tập 45 và 60 phút:

   Duration       min       max      mean
0      45.0  5.193333  9.022222  6.182963
1      60.0  3.586667  7.983333  5.202905

### Đọc dữ liệu từ file `weight.csv` và hợp nhất với dữ liệu đã làm sạch

In [ ]:
# Load the weight.csv file
df_weight = pd.read_csv('/content/weight.csv')

print("Dữ liệu từ weight.csv:")
display(df_weight.head())
print(f"Kích thước dữ liệu weight.csv: {df_weight.shape}")

Dữ liệu từ weight.csv:

         Date  Weight
0  2020/11/20     NaN
1  2020/11/21    65.9
2   020/11/22    65.8
3  2020/11/23    65.8
4  2020/11/24    65.7

Kích thước dữ liệu weight.csv: (43, 2)

### Chuẩn hóa cột 'Date' trong `df_weight` trước khi hợp nhất

In [ ]:
# Ensure 'Date' column in df_weight is in YYYY/MM/DD string format
df_weight['Date'] = pd.to_datetime(df_weight['Date'], errors='coerce').dt.strftime('%Y/%m/%d')

# Drop rows where Date could not be parsed
df_weight.dropna(subset=['Date'], inplace=True)

print("Dữ liệu weight.csv sau khi chuẩn hóa cột Date:")
display(df_weight.head())

Dữ liệu weight.csv sau khi chuẩn hóa cột Date:

         Date  Weight
0  2020/11/20     NaN
1  2020/11/21    65.9
3  2020/11/23    65.8
4  2020/11/24    65.7
5  2020/11/25    65.7

### Hợp nhất dữ liệu

In [ ]:
# Merge df and df_weight on the 'Date' column using an outer merge to keep all dates
df_merged = pd.merge(df, df_weight, on='Date', how='outer', suffixes=('_gym', '_weight'))

print("Dữ liệu sau khi hợp nhất (5 dòng đầu):")
display(df_merged.head())
print(f"Kích thước dữ liệu sau khi hợp nhất: {df_merged.shape}")

Dữ liệu sau khi hợp nhất (5 dòng đầu):

,Duration,Date,Pulse,Maxpulse,Calories,Calories per minute,Weight
0,NaN,'2020/11/12',NaN,NaN,NaN,NaN,NaN
1,NaN,'2020/11/13',NaN,NaN,269.0,NaN,NaN
2,60.0,'2020/11/14',NaN,NaN,NaN,NaN,NaN
3,60.0,'2020/11/16',100.0,120.0,255.7,4.261667,NaN
4,60.0,'2020/11/17',107.0,129.0,347.3,5.788333,NaN

Kích thước dữ liệu sau khi hợp nhất: (95, 7)

### Tự nhận xét và làm sạch dữ liệu sau hợp nhất

In [ ]:
print("Thông tin dữ liệu sau hợp nhất:")
df_merged.info()

print("Số lượng giá trị thiếu sau hợp nhất:")
display(df_merged.isnull().sum())

# Handle missing 'Weight' values: Forward fill if possible, then backward fill
df_merged['Weight'].fillna(method='ffill', inplace=True)
df_merged['Weight'].fillna(method='bfill', inplace=True)

# If any 'Weight' still missing (e.g., if all were NaN or at the very beginning/end and couldn't be filled)
# I will drop rows with missing Weight for daily weight loss calculation, as it's critical.
initial_rows_merged = df_merged.shape[0]
df_merged.dropna(subset=['Weight'], inplace=True)
removed_rows_no_weight = initial_rows_merged - df_merged.shape[0]
print(f"Số lượng hàng bị xóa do thiếu 'Weight' không thể điền: {removed_rows_no_weight}")

# Clean up 'Date' column: remove quotes if present, then convert to datetime
df_merged['Date'] = df_merged['Date'].astype(str).str.replace("'", "", regex=False)
df_merged['Date'] = pd.to_datetime(df_merged['Date'], errors='coerce', format='mixed')

# Drop rows where Date could not be parsed (became NaT)
initial_rows_before_date_drop = df_merged.shape[0]
df_merged.dropna(subset=['Date'], inplace=True)
removed_rows_no_date = initial_rows_before_date_drop - df_merged.shape[0]
print(f"Số lượng hàng bị xóa do không thể chuẩn hóa 'Date': {removed_rows_no_date}")

# Drop rows where 'Duration' or 'Calories' are still missing after merge, as they are needed for analysis
df_merged.dropna(subset=['Duration', 'Calories'], inplace=True)

# Sort by Date for correct weight loss calculation
df_merged.sort_values(by='Date', inplace=True)

print("Dữ liệu sau khi làm sạch thêm:")
display(df_merged.head())
print(f"Kích thước dữ liệu cuối cùng sau làm sạch thêm: {df_merged.shape}")

Thông tin dữ liệu sau hợp nhất:
<class 'pandas.core.frame.DataFrame'>
Index: 46 entries, 3 to 94
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Duration             46 non-null     float64
 1   Date                 43 non-null     object
 2   Pulse                41 non-null     float64
 3   Maxpulse             46 non-null     float64
 4   Calories             46 non-null     float64
 5   Calories per minute  46 non-null     float64
 6   Weight               46 non-null     float64
 7   Previous_Day_Weight  45 non-null     float64
 8   Daily_Weight_Loss    46 non-null     float64
dtypes: float64(8), object(1)
memory usage: 3.6+ KB
Số lượng giá trị thiếu sau hợp nhất:

Duration               0
Date                   3
Pulse                  5
Maxpulse               0
Calories               0
Calories per minute    0
Weight                 0
Previous_Day_Weight    1
Daily_Weight_Loss      0
dtype: int64

Số lượng hàng bị xóa do thiếu 'Weight' không thể điền: 0
Số lượng hàng bị xóa do không thể chuẩn hóa 'Date': 3
Dữ liệu sau khi làm sạch thêm:

/tmp/ipykernel_2989/1209471056.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_merged['Weight'].fillna(method='ffill', inplace=True)
/tmp/ipykernel_2989/1209471056.py:8: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_merged['Weight'].fillna(method='ffill', inplace=True)
/tmp/ipykernel_2989/1209471056.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_merged['Weight'].fillna(method='bfill', inplace=True)
/tmp/ipykernel_2989/1209471056.py:9: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_merged['Weight'].fillna(method='bfill', inplace=True)

,Duration,Date,Pulse,Maxpulse,Calories,Calories per minute,Weight,Previous_Day_Weight,Daily_Weight_Loss
3,60.0,2020-11-16,100.0,120.0,255.7,4.261667,65.9,NaN,0.0
4,60.0,2020-11-17,107.0,129.0,347.3,5.788333,65.9,65.9,0.0
5,60.0,2020-11-17,107.0,129.0,347.3,5.788333,65.9,65.9,0.0
6,60.0,2020-11-17,107.0,129.0,347.3,5.788333,65.9,65.9,0.0
8,45.0,2020-11-19,99.0,119.0,283.0,6.288889,65.9,65.9,0.0

Kích thước dữ liệu cuối cùng sau làm sạch thêm: (43, 9)

### Tính số kg giảm được mỗi ngày

In [ ]:
# Calculate daily weight loss (previous day's weight - current day's weight)
df_merged['Previous_Day_Weight'] = df_merged['Weight'].shift(1)
df_merged['Daily_Weight_Loss'] = df_merged['Previous_Day_Weight'] - df_merged['Weight']

# The first day will have NaN for Daily_Weight_Loss, fill with 0 or drop if not relevant
df_merged['Daily_Weight_Loss'].fillna(0, inplace=True) # Assuming no loss on first day or if previous weight not available

print("Dữ liệu với cột 'Daily_Weight_Loss':")
display(df_merged.head())

Dữ liệu với cột 'Daily_Weight_Loss':

/tmp/ipykernel_2989/4156595040.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_merged['Daily_Weight_Loss'].fillna(0, inplace=True) # Assuming no loss on first day or if previous weight not available

,Duration,Date,Pulse,Maxpulse,Calories,Calories per minute,Weight,Previous_Day_Weight,Daily_Weight_Loss
3,60.0,'2020/11/16',100.0,120.0,255.7,4.261667,65.9,NaN,0.0
4,60.0,'2020/11/17',107.0,129.0,347.3,5.788333,65.9,65.9,0.0
5,60.0,'2020/11/17',107.0,129.0,347.3,5.788333,65.9,65.9,0.0
6,60.0,'2020/11/17',107.0,129.0,347.3,5.788333,65.9,65.9,0.0
8,45.0,'2020/11/19',99.0,119.0,283.0,6.288889,65.9,65.9,0.0

### Tìm và in thông tin chi tiết của những ngày

#### 1. Giảm cân được nhiều nhất và đốt nhiều calo nhất

In [ ]:
# Find day(s) with maximum weight loss (Daily_Weight_Loss should be positive for loss)
max_weight_loss_days = df_merged[df_merged['Daily_Weight_Loss'] == df_merged['Daily_Weight_Loss'].max()]

# Among these, find the one(s) with maximum calories burned
if not max_weight_loss_days.empty:
    max_weight_loss_and_calories_day = max_weight_loss_days[max_weight_loss_days['Calories'] == max_weight_loss_days['Calories'].max()]
    print("Ngày giảm cân được nhiều nhất và đốt nhiều calo nhất:")
    display(max_weight_loss_and_calories_day[['Date', 'Weight', 'Daily_Weight_Loss', 'Calories']])
else:
    print("Không tìm thấy ngày có giảm cân.")

Ngày giảm cân được nhiều nhất và đốt nhiều calo nhất:

        Date  Weight  Daily_Weight_Loss  Calories
90  20201226    63.6                2.3     250.0

#### 2. Đốt nhiều calo nhất nhưng giảm được ít cân nhất (hoặc không giảm cân, hoặc tăng cân)

In [ ]:
# Find day(s) with maximum calories burned
max_calories_days = df_merged[df_merged['Calories'] == df_merged['Calories'].max()]

# Among these, find the one(s) with minimum weight loss (i.e., most positive or least negative Daily_Weight_Loss)
# This implies we are looking for days where high calories were burned, but weight loss was minimal or weight gain occurred.

if not max_calories_days.empty:
    # We want the 'least loss' or 'most gain' so we look for the maximum value of 'Daily_Weight_Loss'
    # among days with max calories, if there are multiple days with max calories.
    min_loss_on_max_calories_day = max_calories_days[max_calories_days['Daily_Weight_Loss'] == max_calories_days['Daily_Weight_Loss'].min()]

    print("Ngày đốt nhiều calo nhất nhưng giảm được ít cân nhất (hoặc tăng cân):")
    display(min_loss_on_max_calories_day[['Date', 'Weight', 'Daily_Weight_Loss', 'Calories']])
else:
    print("Không tìm thấy ngày đốt nhiều calo.")

Ngày đốt nhiều calo nhất nhưng giảm được ít cân nhất (hoặc tăng cân):

            Date  Weight  Daily_Weight_Loss  Calories
20  '2020/12/02'    65.9                0.0     479.0